export const WORLD_ENTITY_STYLES = {
  celestial: {
    rootOutlineColor: 0xdceeff,
    childOutlineColor: 0xffffff,
    rootOutlineWidth: 3,
    childOutlineWidth: 2,
    outlineAlpha: 0.75,
  },
  defense: {
    beamStrokeColor: 0xfff2f2,
    stationStrokeColor: 0xf8fff2,
    stationDetailColor: 0xe2fff0,
    targetStrokeColor: 0xfff4cf,
    targetDetailColor: 0xffdd82,
    launcherStrokeColor: 0xfff2f2,
    beamStrokeWidth: 2,
    stationStrokeWidth: 2,
    targetStrokeWidth: 2,
    launcherStrokeWidth: 2,
    beamStrokeAlpha: 0.9,
    stationStrokeAlpha: 0.9,
    targetStrokeAlpha: 0.92,
    launcherStrokeAlpha: 0.9,
    genericStrokeAlpha: 0.85,
  },
  explosions: {
    ship: {
      outerColor: 0xffa347,
      outerAlpha: 0.28,
      innerColor: 0xfff2bf,
      innerAlpha: 0.92,
      shardColor: 0xff7a45,
      shardAlpha: 0.8,
    },
    missile: {
      outerColor: 0xff9d52,
      outerAlpha: 0.32,
      innerColor: 0xfff0c2,
      innerAlpha: 0.95,
    },
  },
  missile: {
    trailOuterColor: 0xff8f4d,
    trailOuterWidth: 6,
    trailOuterAlpha: 0.1,
    trailInnerColor: 0xffc07a,
    trailInnerWidth: 3,
    trailInnerAlpha: 0.18,
    bodyFillColor: 0xffb36b,
    bodyStrokeColor: 0xfff2d6,
    bodyStrokeWidth: 2,
    bodyStrokeAlpha: 0.95,
    noseGlowColor: 0xfff4d6,
    noseGlowAlpha: 0.22,
    crashedAlpha: 0.35,
  },
} as const;
