import type { SharedMapLayout } from "../types";

export const At3Layout: SharedMapLayout = {
  id: "at3",
  name: "At3",
  spawn: {
    systemId: "aurelia-training",
    orbitRadius: 980,
    orbitDirection: "cw",
  },
  celestialConfigs: [
    {
      id: "aurelia-training:aurelia",
      name: "Aurelia Lab",
      systemId: "aurelia-training",
      parentId: null,
      rootPosition: { x: 0, y: 0 },
      mass: 170000,
      radius: 130,
      color: 0x4d9bff,
      orbitRadius: 0,
      orbitPeriod: 0,
      initialAngle: 0,
      celestialClass: "medium-earthlike-planet",
      weatherLevel: "moderate",
      rockyPalette: "default",
      renderSeed: "aurelia",
    },
    {
      id: "aurelia-training:selene",
      name: "Selene Lab",
      systemId: "aurelia-training",
      parentId: "aurelia-training:aurelia",
      rootPosition: { x: 0, y: 0 },
      mass: 6800,
      radius: 46,
      color: 0xbec9ff,
      orbitRadius: 1200,
      orbitPeriod: 74,
      initialAngle: 0.471,
      celestialClass: "rocky-moon",
      weatherLevel: "none",
      rockyPalette: "slate",
      renderSeed: "selene",
    },
  ],
  defenseConfigs: [
    {
      id: "aurelia-training:selene-darkside-missile",
      name: "Selene Darkside Launcher",
      systemId: "aurelia-training",
      parentId: "aurelia-training:selene",
      weaponType: "torpedo",
      anchorToParent: "dark-side",
      darkSideRelativeToId: "aurelia-training:aurelia",
      scannerRange: 1320,
      lockOnSeconds: 1.6,
      cooldownSeconds: 5.8,
      beamRange: 0,
      beamDamagePerSecond: 0,
      torpedoSpeed: 210,
      torpedoThrust: 420,
      torpedoTurnRate: 5.4,
      radius: 14,
      color: 0xff6b6b,
      orbitRadius: 70,
      orbitPeriod: 0,
      initialAngle: 0,
      shieldCapacity: 0.16,
      shieldRechargePerSecond: 0.03,
    },
  ],
};

export default At3Layout;
