import type { SharedMapLayout } from "../types";
import { createSimpleSystemConfigs } from "../prototype-maps";

const systemId = "enemy-style-sandbox";
const rootId = `${systemId}:aurelia`;
const moonId = `${systemId}:selene`;

const celestialConfigs = createSimpleSystemConfigs(
  systemId,
  "Sandbox",
  { x: 0, y: 0 },
  true,
);

const EnemyStyleSandboxLayout: SharedMapLayout = {
  id: "enemy-style-sandbox",
  name: "Enemy Style Sandbox",
  mapDescription:
    "Single-system style testbed with one of each enemy/entity class: surface launcher, orbital launcher, beam raider, support station, and training targets.",
  spawn: {
    systemId,
    orbitRadius: 980,
    orbitDirection: "cw",
  },
  celestialConfigs,
  defenseConfigs: [
    {
      id: `${systemId}:aurelia-surface-launcher`,
      name: "Aurelia Surface Launcher",
      systemId,
      parentId: rootId,
      weaponType: "torpedo",
      anchorToParent: "fixed",
      scannerRange: 1100,
      lockOnSeconds: 1.2,
      cooldownSeconds: 4.6,
      beamRange: 0,
      beamDamagePerSecond: 0,
      torpedoSpeed: 180,
      torpedoThrust: 340,
      torpedoTurnRate: 4.4,
      radius: 15,
      color: 0xff8f72,
      orbitRadius: 158,
      orbitPeriod: 0,
      initialAngle: Math.PI * 0.58,
      shieldCapacity: 0.2,
      shieldRechargePerSecond: 0.03,
    },
    {
      id: `${systemId}:selene-darkside-launcher`,
      name: "Selene Darkside Launcher",
      systemId,
      parentId: moonId,
      weaponType: "torpedo",
      anchorToParent: "dark-side",
      darkSideRelativeToId: rootId,
      scannerRange: 1320,
      lockOnSeconds: 1.4,
      cooldownSeconds: 5.4,
      beamRange: 0,
      beamDamagePerSecond: 0,
      torpedoSpeed: 210,
      torpedoThrust: 420,
      torpedoTurnRate: 5.4,
      radius: 14,
      color: 0xff6b6b,
      orbitRadius: 70,
      orbitPeriod: 0,
      initialAngle: 0,
      shieldCapacity: 0.16,
      shieldRechargePerSecond: 0.03,
    },
    {
      id: `${systemId}:aurelia-orbital-launcher`,
      name: "Aurelia Orbital Launcher",
      systemId,
      parentId: rootId,
      weaponType: "torpedo",
      anchorToParent: "orbit",
      scannerRange: 5400,
      lockOnSeconds: 2,
      cooldownSeconds: 6.8,
      beamRange: 0,
      beamDamagePerSecond: 0,
      torpedoSpeed: 220,
      torpedoThrust: 440,
      torpedoTurnRate: 5.1,
      radius: 15,
      color: 0xffb07f,
      orbitRadius: 1680,
      orbitPeriod: 108,
      initialAngle: Math.PI * 1.08,
      shieldCapacity: 0.18,
      shieldRechargePerSecond: 0.035,
    },
    {
      id: `${systemId}:aurelia-raider`,
      name: "Aurelia Raider",
      systemId,
      parentId: rootId,
      weaponType: "beam",
      anchorToParent: "orbit",
      scannerRange: 1640,
      lockOnSeconds: 1.2,
      cooldownSeconds: 0,
      beamRange: 460,
      beamDamagePerSecond: 0.6,
      torpedoSpeed: 0,
      torpedoThrust: 0,
      torpedoTurnRate: 0,
      radius: 18,
      color: 0xff7f9a,
      orbitRadius: 1080,
      orbitPeriod: 86,
      initialAngle: Math.PI * 0.14,
      shieldCapacity: 0.3,
      shieldRechargePerSecond: 0.05,
    },
    {
      id: `${systemId}:selene-support-station`,
      name: "Selene Support Station",
      systemId,
      parentId: moonId,
      weaponType: "station",
      anchorToParent: "fixed",
      scannerRange: 0,
      lockOnSeconds: 0,
      cooldownSeconds: 0,
      beamRange: 0,
      beamDamagePerSecond: 0,
      torpedoSpeed: 0,
      torpedoThrust: 0,
      torpedoTurnRate: 0,
      radius: 16,
      color: 0x89ffd0,
      orbitRadius: 70,
      orbitPeriod: 0,
      initialAngle: Math.PI * 0.36,
      shieldCapacity: 0,
      shieldRechargePerSecond: 0,
      refuelRange: 160,
      refuelPerSecond: 0.24,
    },
    {
      id: `${systemId}:training-target-alpha`,
      name: "Training Target Alpha",
      systemId,
      parentId: rootId,
      weaponType: "target",
      anchorToParent: "orbit",
      scannerRange: 0,
      lockOnSeconds: 0,
      cooldownSeconds: 0,
      beamRange: 0,
      beamDamagePerSecond: 0,
      torpedoSpeed: 0,
      torpedoThrust: 0,
      torpedoTurnRate: 0,
      radius: 14,
      color: 0xffd27a,
      orbitRadius: 640,
      orbitPeriod: 46,
      initialAngle: Math.PI * 0.08,
      shieldCapacity: 0,
      shieldRechargePerSecond: 0,
    },
    {
      id: `${systemId}:training-target-beta`,
      name: "Training Target Beta",
      systemId,
      parentId: rootId,
      weaponType: "target",
      anchorToParent: "orbit",
      scannerRange: 0,
      lockOnSeconds: 0,
      cooldownSeconds: 0,
      beamRange: 0,
      beamDamagePerSecond: 0,
      torpedoSpeed: 0,
      torpedoThrust: 0,
      torpedoTurnRate: 0,
      radius: 14,
      color: 0xffd27a,
      orbitRadius: 880,
      orbitPeriod: 62,
      initialAngle: Math.PI * 0.88,
      shieldCapacity: 0,
      shieldRechargePerSecond: 0,
    },
    {
      id: `${systemId}:training-target-gamma`,
      name: "Training Target Gamma",
      systemId,
      parentId: rootId,
      weaponType: "target",
      anchorToParent: "orbit",
      scannerRange: 0,
      lockOnSeconds: 0,
      cooldownSeconds: 0,
      beamRange: 0,
      beamDamagePerSecond: 0,
      torpedoSpeed: 0,
      torpedoThrust: 0,
      torpedoTurnRate: 0,
      radius: 14,
      color: 0xffd27a,
      orbitRadius: 1220,
      orbitPeriod: 78,
      initialAngle: Math.PI * 1.52,
      shieldCapacity: 0,
      shieldRechargePerSecond: 0,
    },
  ],
};

export default EnemyStyleSandboxLayout;
