import type { SharedMapLayout } from "../types";

const systemId = "sol-system-draft";
const sunId = `${systemId}:sol`;
const earthId = `${systemId}:earth`;

const SolSystemDraftLayout: SharedMapLayout = {
  id: "sol-system-draft",
  name: "Sol System Draft",
  mapDescription:
    "Draft solar-system map inspired by Earth's neighborhood: one central star, major planets, and a playable Earth-Luna spawn lane.",
  spawn: {
    systemId,
    anchorBodyId: earthId,
    orbitRadius: 3200,
    orbitDirection: "ccw",
  },
  celestialConfigs: [
    {
      id: sunId,
      name: "Sol",
      systemId,
      parentId: null,
      rootPosition: { x: 0, y: 0 },
      mass: 2400000,
      radius: 300,
      color: 0xffd257,
      orbitRadius: 0,
      orbitPeriod: 0,
      initialAngle: 0,
      celestialClass: "gas-supergiant",
      weatherLevel: "extreme",
      renderPreset: "lava",
      renderSeed: "sol",
    },
    {
      id: `${systemId}:mercury`,
      name: "Mercury",
      systemId,
      parentId: sunId,
      rootPosition: { x: 0, y: 0 },
      mass: 4300,
      radius: 20,
      color: 0xbab6ad,
      orbitRadius: 6800,
      orbitPeriod: 180,
      initialAngle: Math.PI * 0.2,
      orbitDirection: "ccw",
      orbitEccentricity: 0.12,
      orbitRotation: Math.PI * 0.22,
      celestialClass: "small-rocky-planet",
      rockyPalette: "slate",
      renderSeed: "mercury",
    },
    {
      id: `${systemId}:venus`,
      name: "Venus",
      systemId,
      parentId: sunId,
      rootPosition: { x: 0, y: 0 },
      mass: 8200,
      radius: 30,
      color: 0xe0c38c,
      orbitRadius: 9800,
      orbitPeriod: 300,
      initialAngle: Math.PI * 1.1,
      orbitDirection: "ccw",
      orbitEccentricity: 0.03,
      orbitRotation: Math.PI * 0.06,
      celestialClass: "medium-terrestrial-planet",
      rockyPalette: "ochre",
      weatherLevel: "heavy",
      renderSeed: "venus",
    },
    {
      id: earthId,
      name: "Earth",
      systemId,
      parentId: sunId,
      rootPosition: { x: 0, y: 0 },
      mass: 9800,
      radius: 34,
      color: 0x4d9bff,
      orbitRadius: 13400,
      orbitPeriod: 420,
      initialAngle: Math.PI * 0.72,
      orbitDirection: "ccw",
      orbitEccentricity: 0.02,
      orbitRotation: Math.PI * 0.1,
      celestialClass: "medium-earthlike-planet",
      weatherLevel: "moderate",
      renderPreset: "earthlike",
      renderSeed: "earth",
    },
    {
      id: `${systemId}:luna`,
      name: "Luna",
      systemId,
      parentId: earthId,
      rootPosition: { x: 0, y: 0 },
      mass: 1200,
      radius: 10,
      color: 0xdde3ef,
      orbitRadius: 1900,
      orbitPeriod: 80,
      initialAngle: Math.PI * 0.42,
      orbitDirection: "ccw",
      orbitEccentricity: 0.05,
      orbitRotation: Math.PI * 0.34,
      celestialClass: "rocky-moon",
      rockyPalette: "default",
      renderSeed: "luna",
    },
    {
      id: `${systemId}:mars`,
      name: "Mars",
      systemId,
      parentId: sunId,
      rootPosition: { x: 0, y: 0 },
      mass: 5200,
      radius: 26,
      color: 0xc56f4d,
      orbitRadius: 17600,
      orbitPeriod: 580,
      initialAngle: Math.PI * 1.48,
      orbitDirection: "ccw",
      orbitEccentricity: 0.09,
      orbitRotation: Math.PI * 0.36,
      celestialClass: "small-rocky-planet",
      rockyPalette: "rust",
      renderSeed: "mars",
    },
    {
      id: `${systemId}:jupiter`,
      name: "Jupiter",
      systemId,
      parentId: sunId,
      rootPosition: { x: 0, y: 0 },
      mass: 320000,
      radius: 168,
      color: 0xd3aa78,
      orbitRadius: 24600,
      orbitPeriod: 960,
      initialAngle: Math.PI * 0.92,
      orbitDirection: "ccw",
      orbitEccentricity: 0.05,
      orbitRotation: Math.PI * 0.28,
      celestialClass: "gas-supergiant",
      weatherLevel: "heavy",
      renderSeed: "jupiter",
    },
    {
      id: `${systemId}:saturn`,
      name: "Saturn",
      systemId,
      parentId: sunId,
      rootPosition: { x: 0, y: 0 },
      mass: 280000,
      radius: 146,
      color: 0xe5c08f,
      orbitRadius: 32400,
      orbitPeriod: 1360,
      initialAngle: Math.PI * 0.32,
      orbitDirection: "ccw",
      orbitEccentricity: 0.06,
      orbitRotation: Math.PI * 0.52,
      celestialClass: "gas-giant",
      weatherLevel: "moderate",
      renderSeed: "saturn",
    },
    {
      id: `${systemId}:uranus`,
      name: "Uranus",
      systemId,
      parentId: sunId,
      rootPosition: { x: 0, y: 0 },
      mass: 120000,
      radius: 96,
      color: 0x8acfe6,
      orbitRadius: 40200,
      orbitPeriod: 1820,
      initialAngle: Math.PI * 1.12,
      orbitDirection: "ccw",
      orbitEccentricity: 0.05,
      orbitRotation: Math.PI * 0.84,
      celestialClass: "gas-giant",
      weatherLevel: "light",
      renderSeed: "uranus",
    },
    {
      id: `${systemId}:neptune`,
      name: "Neptune",
      systemId,
      parentId: sunId,
      rootPosition: { x: 0, y: 0 },
      mass: 118000,
      radius: 92,
      color: 0x4c76d7,
      orbitRadius: 48200,
      orbitPeriod: 2260,
      initialAngle: Math.PI * 1.72,
      orbitDirection: "ccw",
      orbitEccentricity: 0.04,
      orbitRotation: Math.PI * 1.08,
      celestialClass: "gas-giant",
      weatherLevel: "moderate",
      renderSeed: "neptune",
    },
    {
      id: `${systemId}:pluto`,
      name: "Pluto",
      systemId,
      parentId: sunId,
      rootPosition: { x: 0, y: 0 },
      mass: 2200,
      radius: 18,
      color: 0xbfbbb2,
      orbitRadius: 57800,
      orbitPeriod: 3020,
      initialAngle: Math.PI * 1.62,
      orbitDirection: "ccw",
      orbitEccentricity: 0.24,
      orbitRotation: Math.PI * 0.18,
      celestialClass: "icy-dwarf",
      rockyPalette: "ash",
      renderSeed: "pluto",
    },
  ],
  defenseConfigs: [],
};

export default SolSystemDraftLayout;
